#!/bin/bash

FROM nordicplayground/nrfconnect-sdk:v2.0-branch

ARG USERNAME=vscode
ARG USER_UID=1000
ARG USER_GID=$USER_UID

RUN set -x \
    && groupadd --gid $USER_GID $USERNAME \
    && useradd --uid $USER_UID --gid $USER_GID -m $USERNAME \
    && adduser $USERNAME dialout

USER $USERNAME
